global using AutoFixture;
global using AutoFixture.NUnit3;
global using AutoMapper;
global using Entities;
global using Entities.Entity;
global using Microsoft.Extensions.Logging;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Moq;
global using NUnit.Framework;
global using System.Threading.Tasks;
global using Assert = NUnit.Framework.Assert;
